apiVersion: v1
kind: Service 
metadata:
  name: servicioa
  namespace: exampleistio
  labels:
    app: servicioa
    service: servicioa
spec:
  ports: 
  - port: 5001
    name: http
  selector:
    app: servicioa
---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: servicioa-v1
  namespace: exampleistio
  labels:
    app: servicioa
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: servicioa
  template:
    metadata: 
      labels:
        app: servicioa
        version: v1
    spec:
      containers:
        - name: servicioa
          image: syscomerhub/servicioa:v1
          imagePullPolicy: Always
          ports:
          - containerPort: 5001
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: servicioa
  namespace: exampleistio
spec:
  hosts:
  - "*"
  gateways:
  - app-gateway
  http:
  - route:
    - destination:
        host: servicioa
        port:
          number: 5001
