apiVersion: v1
kind: Service 
metadata:
  name: serviciob
  namespace: exampleistio
  labels:
    app: serviciob
    service: serviciob
spec:
  ports: 
  - port: 5000
    name: http
  selector:
    app: serviciob
---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: serviciob-v1
  namespace: exampleistio
  labels:
    app: serviciob
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: serviciob
  template:
    metadata: 
      labels:
        app: serviciob
        version: v1
    spec:
      containers:
        - name: serviciob
          image: syscomerhub/serviciob:v1
          imagePullPolicy: Always
          ports:
          - containerPort: 5000
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: serviciob
  namespace: exampleistio
spec:
  hosts:
  - "*"
  gateways:
  - app-gateway
  http:
  - match:
    - uri:
        prefix: /api
      headers:
        Api:
          exact: serviciob
    rewrite:
      uri: /
    route:
    - destination:
        host: serviciob.exampleistio.svc.cluster.local
        port:
          number: 5000
