apiVersion: v1
kind: Service 
metadata:
  name: appstatic
  namespace: exampleistio
  labels:
    app: appstatic
    service: appstatic
spec:
  ports: 
  - port: 80
    name: http
  selector:
    app: appstatic
---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: appstatic-v1
  namespace: exampleistio
  labels:
    app: appstatic
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: appstatic
  template:
    metadata: 
      labels:
        app: appstatic
        version: v1
    spec:
      containers:
        - name: appstatic
          image: registry.gitlab.com/andor-pierdelacabeza/dockerstatic:v1
          imagePullPolicy: Always
          ports:
          - containerPort: 80
          
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: app-gateway
  namespace: exampleistio
spec:
  selector:
    istio: ingressgateway # use istio defautl controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "138.197.234.107"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: appstatic
  namespace: exampleistio
spec:
  hosts:
  - "*"
  gateways:
  - app-gateway
  http:
  - route:
    - destination:
        host: appstatic
        port:
          number: 80
